### ISSUE TITLE
Some 1.0.4 compatible mods that require an override/update

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#1773]
- [x] DMagic Orbital Science #1790
- [x] MSI's Infernal Robotics - Model Rework (core+expansion) #1804
- [x] Portable Science Container #1802
- [x] Mission Controller 2 #1803
- [x] Routine Mission Manager  #1801
- [x] S.A.V.E. #1795
- [x] Crew Portraits (also needs a homepage set) #1792
- [x] FASA Launch Clamps and Towers  #1789
- [x] Hullcam VDS #1798
- [x] In game notes / notepad / checklist  #1799
- [x] KSP Achievements #1794
- [x] Star Trek: TOS colored Space Suits #1791
- [x] Station Science KSP-CKAN/CKAN-meta#675
- [x] Stock Fuel Switch #1788
- [x] TACLS Mining #1800

**Comment by plague006** [comment]
going to keep the issue open until they're merged (just in case)

**Comment by Murdabenne** [comment]
Havent been any in a couple days other than the bots.  Jenkins is down too.
