### ISSUE TITLE
Craft mods waiting on updates to dependencies and/or update by author

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#1860]
Original PR   --   KerbalStuff link
* [ ] #1617 - [UH60 Blackhawk](https://kerbalstuff.com/mod/919)
* [ ] #1616 - [UDL4 Cheyenne Dropship](https://kerbalstuff.com/mod/918)
* [ ] #1615 - [M-577 Rhino Armored Personel Carrier](https://kerbalstuff.com/mod/917)
* [ ] #1613 - [The HAWK Space fighter](https://kerbalstuff.com/mod/916)
* [x] #2312 - [SHADO](https://kerbalstuff.com/mod/1168)
* [ ] #2313 - [Federation Type F Shuttle](https://kerbalstuff.com/mod/1169)

All 6 have in common: a requirement for [RetroFuture](http://forum.kerbalspaceprogram.com/threads/84054), whose latest version `v1.7.2b` was released on 2014-12-11 is for KSP `0.25.0`. So there is no `0.90` release, and all craft are for ksp_ver `0.90`. For clarity, these craft mods were published post-`1.0` meaning the author explicitly wanted `0.90`.

Further, the readme (identical for all 5) says:
```
EDIT THIS (OR ADD THIS) LINE TO THE CFG FILE FOR AIRCRAFT, Then Tweak it a bit!
node_stack_top = 0.023, 4.762, -1.208, 0.0, 1.0, 0.0, 1 //COCKPIT
(Fuselage Section)
```
Meaning users are meant to manually edit CFG files: something we can't accomplish with our current toolset.

So these 6 are blocked by other mod and blocked by mod author.

There are 5 likely outcomes I see:

1. RetroFuture gets an update for ksp `0.90` and the mods remain blocked by mod author.
2. RetroFuture gets an update for ksp `0.90` and we ignore the change required for the CFG files in order to release.
3. RetroFuture gets an update for ksp `1.0` or later and the mods remain blocked by other mod.
4. RetroFuture doesn't update and the mods remain blocked by other mod.
5. Mod author updates depends and incorporates fix.

None of those 5 options are, in my estimation, likely to occur in the near future.

I'd like to propose we close the PRs and leave this as an issue. We consolidate issues/PRs and in case anything changes we have an at-a-glance view of all the outstanding mods with these issues. Further, this will allow us to add any further mods with the same issues (the mod author is prolific).

---

* [x] [A6Intruder](https://kerbalstuff.com/mod/839) -- [New KS link](https://kerbalstuff.com/mod/1243)
* [x] [A7Corsair2](https://kerbalstuff.com/mod/810)
* [x] [AV8HarrierWITHTRUEVTOLFlight](https://kerbalstuff.com/mod/877)
* [x] [EF2000EuroFighter](https://kerbalstuff.com/mod/860)
* [x] [F14CTomcat](https://kerbalstuff.com/mod/849)
* [x] [F15DCStrikeEagle](https://kerbalstuff.com/mod/870)
* [x] [F18ASuperHornet](https://kerbalstuff.com/mod/840)
* [x] [F22Lightning2OrRaptor](https://kerbalstuff.com/mod/852)
* [x] [F35BSTOLStealthMultiroleFighter](https://kerbalstuff.com/mod/881)
* [x] [F5ATalonFighterAggressor](https://kerbalstuff.com/mod/884)
* [x] [FairchildRepublicA10Warthog](https://kerbalstuff.com/mod/853)
* [x] [MIG29Fulcrum](https://kerbalstuff.com/mod/876)
* [x] [SukhoiSU27Flanker](https://kerbalstuff.com/mod/882)
* [x] [F16FightingFalcon](https://kerbalstuff.com/mod/854)

All 14 have in common: a requirement for [AircraftIVAHelmet](https://kerbalstuff.com/mod/872), whose KerbalStuff page is recently removed by the author, which 'breaks' all the above mods because of an missing dependancy.

**Comment by plague006** [comment]
I'll take another look at these to see if they're updated at KSP 1.1 and if they aren't I'll close this.

**Comment by Olympic1** [comment]
Updated the list with more mods who require an missing dependancy cause of author deleted the KS page.
