### ISSUE TITLE
Mods requiring overwriting to complete (incl. KerbinSide modules)

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#2179]
To be clear: these mods can all be integrated in "fragile" fashions where there are tons of filters and files explicitly installed, the problem with those is small changes to the files/file structure breaks the whole scheme. These mods are waiting on https://github.com/KSP-CKAN/CKAN/issues/1311 to have easier/more stable install methods.

  Original PR   --   KerbalStuff/Forum link
- [x] #1787 - [Kerbol 4X](https://kerbalstuff.com/mod/970/Kerbol%204X)
- [ ]  #2091 - [Kerbin-Side Ground-Control](https://kerbalstuff.com/mod/1073/Kerbin-Side%20Ground-Control)
- [ ] #2166 - [KerbinSideCORE](https://kerbalstuff.com/mod/1099/KerbinSide%20CORE)
- [ ] #2298 - [KerbinSide Kampus](https://kerbalstuff.com/mod/1160/KerbinSide%20Kampus)
- [ ] #2335 - [KerbinSide Skyways](https://kerbalstuff.com/mod/1173/KerbinSide%20Skyways)
- [ ] #2346 - [KerbinSide KSC2](https://kerbalstuff.com/mod/1178/KerbinSide%20KSC2)
- [x] KSP-CKAN/CKAN-meta#351 - [RemoteTech_XF](http://forum.kerbalspaceprogram.com/threads/108669-0-90-RemoteTech-XF-RemoteTech-v-1-6-3)
- [x] #2395 - [tkw HotRockets fx texture](https://kerbalstuff.com/mod/1200/tkw%20HotRockets%20fx%20texture)
- [x] #2348 - [halo scorpion tank](https://kerbalstuff.com/mod/1179/halo%20scorpion%20tank)
- [ ] #3245 - [Versatile Toolbox System](https://github.com/KSP-CKAN/NetKAN/pull/3245) (overwriting can optimize this install)

**Comment by plague006** [comment]
Per the thread RemoteTech_XF is being integrated into RT proper.

**Comment by plague006** [comment]
tkw HotRockets fx texture and halo scorpion tank were KS mods

**Comment by plague006** [comment]
Kerbol 4X was KS-only.

**Comment by plague006** [comment]
That leaves kerbinside and Versatile Toolbox which can have their installs improved with overwriting. We all know about kerbinside and VTS hasn't updated for 1.1. Closing this and if we ever need later on we can search to find it easily enough.
