### ISSUE TITLE
KSBot PR consolidation for amankduffers

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/NetKAN#2282]
These PRs all fall under the same author so probably have similar structures. It has the added benefit of cleaning the PR list a bit. The following mods need to be added:

- [x] #2238 - [heatshield tile](https://kerbalstuff.com/mod/1130/heatshield%20tile)
- [x] #2242 - [M12 LRV "warthog"](https://kerbalstuff.com/mod/1133/M12%20LRV%20%22warthog%22)
- [x] #2250 - [UNSC Pillar of Autumn](https://kerbalstuff.com/mod/1138/UNSC%20Pillar%20of%20Autumn)
- [x] #2253 - [covenant capital ship](https://kerbalstuff.com/mod/1141/covenant%20capital%20ship)
- [x] #2264 - [halo character costumes](https://kerbalstuff.com/mod/1149/halo%20character%20costumes)
- [x] ~~#2348 - [halo scorpion tank](https://kerbalstuff.com/mod/1179/halo%20scorpion%20tank)~~

**Comment by plague006** [comment]
Had another look at these mods and they'll take a decent amount of work. Kicking them down the road again, no idea when I'll get to them.

**Comment by plague006** [comment]
#2348 - halo scorpion tank moved to #2179 as it wants to overwrite files from `KerbalFoundries`

**Comment by plague006** [comment]
All mods either moved to another issue or have open PRs, closing this.
