### ISSUE TITLE
[Feature]: Add first-person tag

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/NetKAN#9859]
### Problem

There's currently not a great tag to use for mods that are associated with playing from IVA mode.  Right now most of them use "crewed" but there are lots of crewed parts that don't have IVAs and some things related to IVAs that have nothing to do with crew (probecontrolroom etc).

### Suggestion

We should standardize a new tag.  After discussion with HebaruSan, `first-person` seems to be the best choice.  `IVA` was considered but is less desirable because it requires familiarity with the acronym.

There are 3 parts to this task:

- [x] Add the tag to the documentation
  https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags
- [x] Add the tag to existing KSP1 netkans - #9887
  - ~~ALCORIVAPatch~~ (frozen)
  - ASETAvionics
  - ASETProps
  - AvionicsSystems
  - B9-props
  - DE-IVAExtension
  - FreeIva
  - HabTechProps
  - kOSPropMonitor
  - KSAIVAUpgrade
  - MK12PodIVAReplacementbyASET
  - Mk1LanderCanIVAReplbyASET
  - Mk3ShuttleMidDeckIVARefurbished
  - NearFutureProps
  - ProbeControlRoomRecontrolled
  - QuickIVA
  - RasterPropMonitor
  - RasterPropMonitor-Core
  - Reviva
  - StarilexMk1NeedleIVA
  - StarshipExpansionProjectIVA
  - StationPartsExpansionRedux-IVAs
  - TDProps
  - ThroughTheEyesOfaKerbal
  - VesselView-UI-RasterPropMonitor
  - VexarpIVA
- [x] Add the tag to existing KSP2 netkans - KSP-CKAN/KSP2-NetKAN#109
  - KerbalView
- [x] Add the tag to the [metadata webtool](https://github.com/KSP-CKAN/metadata-webtool/blob/469f92686e9e93f0bd34229d902a10be55b4a340/refresh_datajs.py#L145-L204) - KSP-CKAN/metadata-webtool#48
- [ ] See if the tag can be auto-detected by the mod analyzer (look for Spaces or Props folders, INTERNAL or PROP in configs, etc)

**Comment by HebaruSan** [comment]
(Rearranged the checkboxes slightly to reflect the ordering that I think would work best.)

Updating the existing netkans would be easy enough to do in a big pull request. Do you want to start that? I know GitHub's web UI doesn't make it trivial to update multiple files, so I can assist with that piece.
